### ISSUE TITLE
Request is not defined

### ISSUE THREAD

**Issue by estanislaobosch** [freerangeeggs/PostToOffice365Connector#25]
Task         : Post to Office365 Connector
Description  : Sends a message to an Office365 connector.
Version      : 1.0.313
Author       : Brett McKenzie
Help         : See here to [access the connectors for either Microsoft Teams or Office 365](https://dev.outlook.com/Connectors)

##[error]Request is not defined

**Comment by estanislaobosch** [comment]
I tried adding
```
  - task: UseNode@1
    inputs:
      version: '18.x'
```
to force node version before the PostToOffice365Connector task but I still get the same error

**Comment by freerangeeggs** [comment]
Hey @estanislaobosch

This should be cleared up now. Sometimes it takes a day for the agent to update with the new task so if you don't get it working immediately it may be that.

Apologies for the late reply on this, I thought it had been sorted as I was seeing telemetry that it was running.
