### ISSUE TITLE
Wrong e-mail ’Subject’ in the case of Office 365 Group

### ISSUE THREAD

**Issue by vipel** [freerangeeggs/PostToOffice365Connector#8]
Visual Studio Marketplace | Post To Office 365 Connector issue:
E-mail ‘Subject’ gets Message (‘msg’) parameter value in the case of Office 365 Group.
It should get Title (‘title’) parameter value.

**Comment by freerangeeggs** [comment]
Hi @vipel,

Letting you know I believe I have resolved this, but it can take time (days) for the task updates to propagate through Azure Pipelines.
